apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: review-collector
  labels:
    app: collector
    component: review-collector
spec:
  type: ClusterIP
  selector:
    app: collector
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
